### ISSUE TITLE
Custom response if no route has been found

### ISSUE THREAD

**Issue by l2ig** [l2ig/aqua#10]

**Comment by ajanieniolasolomon** [comment]
Create a middleware to handle such an instance by checking each route first.


app.register((req:any, res) => {
  
   if(req.url.toString()=='/auth' || req.url.toString()=='/reg'){
       return res;
   }else{
   let re =req.headers;
    var obj = new Headers(re);

    if(re.get('authorization')){

        let values =re.get('authorization').split(' ')[1];

        validateJwt(values,key).then((ress)=>{
           answer=ress;
        
        }).catch((err)=>{
            err='Bad Token';
        })
    }
   else{
       err='No token found';
   }


return answer?res: {
    statusCode: 401,
   
    
    content: err
};
}

});

**Comment by l2ig** [comment]
I now introduced the `provideFallback` function for handling requests with no matching route. 
Example: [Provide own fallback handler](https://github.com/l2ig/aqua#provide-own-fallback-handler)
