### ISSUE TITLE
Feature Request: Wildcard Routing

### ISSUE THREAD

**Issue by jpowersdev** [l2ig/aqua#15]
Right now, I'm using `app.provideFallback` to handle serving assets. Do you have any plans for wildcard routing support? For example, `app.get('/assets/*', ...)`.

**Comment by l2ig** [comment]
Great idea, thanks for suggesting! I'll definitely add this feature in the coming days.

**Comment by l2ig** [comment]
You're now able to provide a RegExp object instead of a string and receive the matches.
-> https://github.com/l2ig/aqua#regex-paths

In your case, you could now handle your asset requests the following way:
```typescript
app.get(new RegExp("\/assets\/(.*)"), (req) => {
    const requestedAsset = req.matches[0];
    // ...
});
```
