### ISSUE TITLE
Feature Request: serveTLS Support

### ISSUE THREAD

**Issue by bdearborn** [l2ig/aqua#17]
Great web framework! Any plans to implement https?

`import { serveTLS } from "https://deno.land/std/http/server.ts";

    const body = new TextEncoder().encode("Hello HTTPS");
    const options = {
      hostname: "localhost",
      port: 443,
      certFile: "./path/to/localhost.crt",
      keyFile: "./path/to/localhost.key",
    };

for await (const req of serveTLS(options)) {
  req.respond({ body });
}`

**Comment by l2ig** [comment]
Thanks for the great feature request! I'll take a look at how to implement it in the best way in the coming days.

**Comment by l2ig** [comment]
Thanks again for your great suggestion, I now added TLS support.
You can read more about it here: https://github.com/l2ig/aqua#tls
