### ISSUE TITLE
Consider using Pagic to build the website?

### ISSUE THREAD

**Issue by xcatliu** [l2ig/aqua#19]
[Pagic](https://pagic.org) is a static site generator powered by Deno + React

Here are some demos:

- [pagic.org](https://pagic.org)
- [Deno X ranking](https://yoshixmk.github.io/deno-x-ranking/)
- [TypeScript 入门教程](https://ts.xcatliu.com/)

Ask me anything if you have some problem.

**Comment by l2ig** [comment]
Thanks for this automated issue that is in no way related to this repo.
If you would like to get Pagic implemented in this project, create a PR or be more specific.
