### ISSUE TITLE
File upload feature

### ISSUE THREAD

**Issue by l2ig** [l2ig/aqua#28]
File uploading would be a great feature, I think.

**Comment by bdearborn** [comment]
Could this be implemented using one of the standard libraries?

See:
[https://deno.land/std@0.82.0/mime/multipart.ts](https://deno.land/std@0.82.0/mime/multipart.ts)

**Comment by l2ig** [comment]
Yes, that's the plan. I'm currently just struggling with the parsing of the POST content.
If you'd like to help or got some tips, I pushed my current code to the [file-upload branch](https://github.com/l2ig/aqua/tree/file-upload). It's currently only working if just one file is getting POSTed.

Btw, your earlier issue already helped me a ton because I couldn't figure out why not all of the file content is getting read when I started working on this file upload feature. :+1:

**Comment by bdearborn** [comment]
Glad I am able to help! I will pull that branch and see if I am able to assist later this week.

The following is a good example that you may be able to reference:
[https://deno.land/x/oak_upload_middleware@Denoland](https://deno.land/x/oak_upload_middleware@Denoland)

**Comment by l2ig** [comment]
Okay, I got it working now. I actually did the parsing myself and not used `MultipartReader`. I'll now compare the performance of both versions in the next days and decide whether the performance improvement of writing it from scratch is worth the struggle of maintaining it for me.

**Comment by l2ig** [comment]
I decided to go with the "from scratch" option. It doesn't need file system access and is about 40% faster.

**Comment by bdearborn** [comment]
Awesome, good work and thank you!
