### ISSUE TITLE
Bundle error.

### ISSUE THREAD

**Issue by michailVestnik** [l2ig/aqua#36]
IF i run command ` deno bundle https://deno.land/x/aqua@v1.0.16/mod.ts aqua.js ` and run with local import - i see the error. 
But if download repository and delete this lines in mod.ts - 

```

import Aqua from "./aqua.ts";
export default Aqua;

```

can be run bundler locally - ` deno bundle mod.ts aqua.js ` and run again - everything works fine.
(warning - in deno 1.6.3 new bundler and there are often problems with it, i make bundle with 1.5.4 version)
You may find this observation useful

Спасибо!

**Comment by l2ig** [comment]
Could you tell me what you are using the Deno bundle command for? I don't quite get why you would bundle a server-side app

**Comment by michailVestnik** [comment]
I work on the principle of frontend development. :-)
In a front we connect js like this: ` <script src="JS/main.js"></script> `
Deno bundle command allows you to use a similar method: 
1. we run bundle and get a ready-made library, as if it is some kind of script on the frontend.
2. next, we connect it in the main file: ` import { module } from './local_module.js' `
as a result, we get a project management structure similar to the frontend.

```

modules_folder
    aqua.js
    dndb.js
    djwt.js
    more_modules.js ...
    
```

I know this is not a common and not quite right method but it
1. is very convenient for a beginner in the backend. 
2. I control all the code of the entire application without caching.

**Comment by l2ig** [comment]
I don't think there is an easy way of fixing it right now.
This bug has already been fixed in SWC (https://github.com/swc-project/swc/pull/1264), but I think it hasn't landed in the Deno CLI yet.

Here's a quick fix:
Use `deno bundle https://deno.land/x/aqua@VERSION/aqua.ts aqua.js` instead of `deno bundle https://deno.land/x/aqua@VERSION/mod.ts aqua.js`.

**Comment by michailVestnik** [comment]
Спасибо!
