### ISSUE TITLE
Redirect crash app

### ISSUE THREAD

**Issue by michailVestnik** [l2ig/aqua#39]
Hi.
I wrote simple test and want share it with you.

Code with your examples:

```

import Aqua from 'https://deno.land/x/aqua/mod.ts' 

const app = new Aqua(8080)

app.serve('static', '/')

app.get('/', async (request) => {
    return await app.render('static/index.html')
})

app.get('/test.html', (request) => {
    return { 
        redirect: '/'
    }
})

app.post('/test', (request) => {
    return { 
        redirect: '/testRedirect'
    }
})

app.register((req, res) => {
    const testData = 'Test string'
    res.content = res.content.replace('- aquaTest -', testData)
    return res
})

// deno run --allow-read --allow-write --allow-net --watch --unstable app.js

```

run it!

![2](https://user-images.githubusercontent.com/75129392/105851770-ddbb5e80-6026-11eb-8eae-cc0ed57a013f.jpg)

how can I fix this?

**Comment by l2ig** [comment]
It's not yet possible to replace the content of a static file if that's what you are trying to achieve. I'm working on adding this feature in the next coming days thanks to this issue.

Regarding your problem:
Not all responses have a `content` key, for example, a `RedirectResponse` has none, so you would need to check if there's a `content` key.
```typescript
res.content = res.content?.replace('- aquaTest -', testData)
```

The wrong example shown in the README is going to be changed once I added the possibility to replace the content of static files.

Thanks for opening this issue :)

**Comment by l2ig** [comment]
Middlewares are now (v1.0.19) able to manipulate raw file data.
Please take a look at the new middleware example.

**Comment by michailVestnik** [comment]
Thanks!
But there is still a question!

in the new example, everything works well!
Code:

![1](https://user-images.githubusercontent.com/75129392/106072976-90391180-614c-11eb-93a4-a1ed11060f35.jpg)

And result ...

![2](https://user-images.githubusercontent.com/75129392/106073225-fc1b7a00-614c-11eb-87f5-c92e98fa3383.jpg)

but if you still declare the template in app.register but it is not in the document - nothing happens!

1. Add more

![3](https://user-images.githubusercontent.com/75129392/106073741-fa9e8180-614d-11eb-8146-932973e3973c.jpg)


2. in HTML 

![4](https://user-images.githubusercontent.com/75129392/106073789-0ee27e80-614e-11eb-936c-7c04463b45a4.png)

3. and result 

![5](https://user-images.githubusercontent.com/75129392/106073821-1d309a80-614e-11eb-9734-6e37ad461878.jpg)

replace not working

I really love aqua for being able to use such simple templating without connecting dejs, denjucks and more modules, maybe can I fix it somehow? -)

**Comment by l2ig** [comment]
It's because you aren't piping the return value to the other replacement line.
What you're trying to achieve should be something like this:
```typescript
    res.content = textContent?.replace("- aquaTest1 -", testData1)
    res.content = res.content?.replace("- aquaTest2 -", testData2)
```

**Comment by michailVestnik** [comment]
Of course, sorry this is my mistake.
Thank you very much! You've helped me a lot!
