### ISSUE TITLE
Feature Request: view engine friendly support

### ISSUE THREAD

**Issue by YasminaKarad** [l2ig/aqua#41]
# Issue

Hello! 
Is it possible to add seamless DEJS support? 
Like this:

```js

import Aqua from 'https://deno.land/x/aqua/mod.ts'
import { renderFile } from 'https://deno.land/x/dejs@0.9.3/mod.ts'

const app = new Aqua(3100)

app.serve('static', '/')

app.get('/', async (request, response) => {
    return await renderFile('static/index.html', {
        test: 'test string render',
    })
})

```

Example:
https://deno.land/x/abc@v1.2.6/examples/template/main.ts

If I missed something, please add an example!

## versions

Deno 1.7.5
Aqua 1.0.19

**Comment by l2ig** [comment]
I'll take a look into this buffer error. For now, you should be able to use the dejs `renderFileToString` function.

**Comment by l2ig** [comment]
Oh, makes sense, the return value is just a buffer, so you would need to convert it to a `Uint8Array` first.

Allowing buffers as a return type in request handlers would just add unnecessary complexity.
