### ISSUE TITLE
[Question] File Uploading

### ISSUE THREAD

**Issue by hokkqi** [l2ig/aqua#47]
So I saw in the README that Aqua supports uploading Files (or Images at least).
I'm kind wondering what code I'd need to write to support uploading files for my small server app.

I'm currently using insomnia.rest, which supports Multipart Forms and binary file uploads but I don't really understand how to actually write the code needed to get the small snippet at the end of the readme to work how it should

**Comment by hokkqi** [comment]
Seems like Insomnia just didn't like ~something~, after copying a bit of it's generated code and editing it, it works and files show up in req.files

the cURL command I used was 
```bash
curl --request POST \
  --url http://localhost:3000/upload \
  --header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
  --form "=@/path/to/file" \
  --form "=@/path/to/file"
  ```

If you paste that into Insomnia, it should properly import the needed stuff and actually send the file

**Comment by l2ig** [comment]
Hey @hokkqi, thanks for opening this issue and I'm glad you seem to have found a solution. Tbh, the file upload _should_ be pretty steady, but I didn't allocate too much time into testing, so feel free to open another issue if you encounter any new problems. 👍

**Comment by hokkqi** [comment]
@l2ig Will do! 
I'll probably just use curl or a part of code i've written before if I need to do any kind of bulk uploading or testing, for now!
