### ISSUE TITLE
How to send file upload request using javascript?

### ISSUE THREAD

**Issue by kitepad** [l2ig/aqua#54]
I'm using your demo code to run a sample upload server:
`import Aqua from "https://deno.land/x/aqua/mod.ts";

const app = new Aqua(3100);

app.get("/", (req) => {
    return "Hello, World!";
});

app.post("/upload", async (req) => {
    const { newProfilePicture } = req.files;
    //return newProfilePicture;
    await Deno.writeFile(newProfilePicture.name , new Uint8Array(await newProfilePicture.arrayBuffer()));
    
    return "Uploaded!";
});`

But told me : error: Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    await Deno.writeFile(newProfilePicture.name , new Uint8Array(await newProfilePicture.arrayBuffer()));

My access code is like below:
`    var resp = await fetch("http://127.0.0.1:3100/upload", {
      method: "POST",
      headers: [["Content_Type","multipart/form-data"],["Content-Disposition","attachment; filename=test"]
    ],
      body: dataToSend
    });`

Would you give me right sample code using javascript which can upload file successfully?

**Comment by l2ig** [comment]
This should help you out:
```javascript
const file = /* maybe document.querySelector(...).files[0] or new File(...) or new Blob(...) */ null;
const uploadData = new FormData();
uploadData.append("newProfilePicture", file);

await fetch("http://127.0.0.1:3100/upload", { method: "POST", headers: new Headers({ "Content-Type": "multipart/form-data" }), body: uploadData });
```

If you need any further help, just comment :+1:

**Comment by kitepad** [comment]
Thanks for your help.
