### ISSUE TITLE
Modify response in middleware

### ISSUE THREAD

**Issue by shyim** [l2ig/aqua#7]
As I see currently it's not possible to manipulate the response?
I was thinking about a session middleware

**Comment by l2ig** [comment]
I now changed the request object that is being passed to the middleware function in f564eafbffdcc7e838860f5e4d8aab17070bdedf.

You are now able to use the response functions:
```typescript
req.setCookie("hello", "world") // Sets a cookie with the name 'hello' and the value 'world'
req.setHeader("Access-Control-Allow-Origin", "*") // Corresponds to 'Access-Control-Allow-Origin: *'
req.setStatusCode(404) // Page returns with the status code 404
```

Was this what you meant?

**Comment by shyim** [comment]
Maybe.
Do I set the header cookie on the request? 🤔?

**Comment by l2ig** [comment]
Yes, these functions set the headers on the response. Maybe I should rename them to something like `setResponseCookie`?

I also thought about also passing a `response` object to the function that handles such things.

**Comment by l2ig** [comment]
I changed the way of how to provide headers, cookies & the status code in e74361aba5a8dab59c2388f06449b72247cf96ed.
I hope that makes everything easier to understand.

**Comment by shyim** [comment]
Looks fine for me :) Thanks!
