### ISSUE TITLE
Invalid route invoked

### ISSUE THREAD

**Issue by csabaokros** [l2ig/aqua#73]
While experimenting with Aqua, I found an issue with how routes are invoked. Given the following routes:
```js
app.get('/:key', GetKey)
app.post('/:key/:value', SetKey)
```

A GET request to `/hello/world` will invoke `SetKey` function, which should only be ran in case of a POST request.

I believe the problem lies in [Router.findRouteWithMatchingURLParameters](https://github.com/l2ig/aqua/blob/main/router.ts#L8), where the route's method is not taken into account.

**Comment by l2ig** [comment]
Thanks for opening this issue! I'll fix this asap

**Comment by l2ig** [comment]
Landed in v1.2.4 (https://deno.land/x/aqua@v1.2.4)

Thanks again for reporting this! :)
