### ISSUE TITLE
Alternative for app.render in 1.3.0?

### ISSUE THREAD

**Issue by huydhoang** [l2ig/aqua#81]
Hi,
I've just tried the latest version 1.3.0.
When trying to render an HTML document, I got this error message:

```bash
Property 'render' does not exist on type 'Aqua'.deno-ts(2339)
```

Checking the release notes, I've found that `render` is "removed from the public Aqua class".
It seemed simple and intuitive enough, so I'm wondering why the remove?

What is the recommended way for serving HTML files from now on?

**Comment by l2ig** [comment]
Hi, the `render` function wasn't used internally anymore for a long time, and therefore I decided to remove it, since it would essentially just be dead code.

The function looked like this, so feel free to implement it yourself or let me know if you have any strong opinion on this topic.
```typescript
async function render(filePath: string): Promise<string> {
  try {
    return new TextDecoder().decode(await Deno.readFile(filePath));
  } catch (error) {
    if (error instanceof Deno.errors.PermissionDenied) {
      return "Please run your application with the '--allow-read' flag.";
    }

    return "Could not render file.";
  }
}
```

You can find the full changelog here: https://github.com/l2ig/aqua/releases/tag/v1.3.0

**Comment by huydhoang** [comment]
@l2ig Thanks for the quick response. I was curious, not having a strong opinion here.
As I was implementing an HTTP server with Deno from scratch. I soon realized switching to an existing framework might be a better idea. It'd take out some weight from the current workload, like implementing URL redirection and stuff.

So is `Deno.readFile` the recommended way to serve HTML from your perspective?

I was using serveFile and serveFallback, taken out of the standard HTTP server code by Deno. It worked but I was hoping `Aqua` to replace it entirely.

```typescript
const encoder = new TextEncoder();

const MEDIA_TYPES: Record<string, string> = {
  '.md': 'text/markdown',
  '.html': 'text/html',
  '.htm': 'text/html',
  '.json': 'application/json',
  '.map': 'application/json',
  '.txt': 'text/plain',
  '.ts': 'text/typescript',
  '.tsx': 'text/tsx',
  '.js': 'application/javascript',
  '.jsx': 'text/jsx',
  '.gz': 'application/gzip',
  '.css': 'text/css',
  '.wasm': 'application/wasm',
  '.mjs': 'application/javascript',
  '.svg': 'image/svg+xml',
};

/** Returns the content-type based on the extension of a path. */
function contentType(path: string): string | undefined {
  return MEDIA_TYPES[extname(path)];
}

/**
 * Returns an HTTP Response with the requested file as the body
 * @param req The server request context used to cleanup the file handle
 * @param filePath Path of the file to serve
 */
const serveFile = async (
  req: ServerRequest,
  filePath: string
): Promise<Response> => {
  const [file, fileInfo] = await Promise.all([
    Deno.open(filePath),
    Deno.stat(filePath),
  ]);
  const headers = new Headers();
  headers.set('content-length', fileInfo.size.toString());
  const contentTypeValue = contentType(filePath);
  if (contentTypeValue) {
    headers.set('content-type', contentTypeValue);
  }
  req.done.then(() => {
    file.close();
  });
  return {
    status: 200,
    body: file,
    headers,
  };
};

const serveFallback = (_req: ServerRequest, e: Error): Promise<Response> => {
  if (e instanceof URIError) {
    return Promise.resolve({
      status: 400,
      body: encoder.encode('Bad Request'),
    });
  } else if (e instanceof Deno.errors.NotFound) {
    return Promise.resolve({
      status: 404,
      body: encoder.encode('Not Found'),
    });
  } else {
    return Promise.resolve({
      status: 500,
      body: encoder.encode('Internal server error'),
    });
  }
};
```

**Comment by l2ig** [comment]
Initially, `render` was just used to get the content of a text file. For the sole purpose of responding with a file's content, I like your proposed code much better. So depends on what you're trying to achieve in the end I guess

**Comment by huydhoang** [comment]
Thanks, your answer cleared my thought : )
