### ISSUE TITLE
[Question] How to get ? parameters?

### ISSUE THREAD

**Issue by PixelPage-YT** [l2ig/aqua#90]
Hello,
i need ? parameters for my login, e.g. localhost:3100/login?code=supercoolcode
Are they already implemented?

**Comment by l2ig** [comment]
Hi, yes, you can get them from the `req.query` object.
```typescript
app.get("/login", (req) => {
  const loginCode = req.query.code;

  return "Hello, World!";
});
```

**Comment by PixelPage-YT** [comment]
And is there an implementation for websockets? I don't like the deno one

**Comment by l2ig** [comment]
No custom one, but you could probably make any user-land implementation like [x/websocket](https://deno.land/x/websocket@v0.1.3) work through `req.raw`/`req.conn`.

Haven't tried it though. Also, If you wan't, feel free to describe your perfect API for working with WebSockets, and I will take a look on how to implement it.

**Comment by PixelPage-YT** [comment]
Ok, x/websocket was exactly what i searched for.
Last question, is there a way to disable cors in aqua?

**Comment by l2ig** [comment]
Sure
```typescript
// Set the header for all routes
app.register((_res, res) => {
  if (!res.headers) res.headers = {};
  res.headers["Access-Control-Allow-Origin"] = "*";
  return res;
}, MiddlewareType.Outgoing);

// Set the header for only one route
app.get("/", (_req) => {
  return {
    headers: {
      "Access-Control-Allow-Origin": "*"
    },
    content: "Hello World!"
  };
});
```

**Comment by kuspoes** [comment]
> 

Hi,
I tried to disable cors using the code above, but it doesn't seem to work properly.

I'm still getting blocked from CORS policy

**Comment by l2ig** [comment]
Do you have a reproducible example @kuspoes?
