### ISSUE TITLE
Cookies : add more control over creation

### ISSUE THREAD

**Issue by LoganTann** [l2ig/aqua#99]
Hello, I'm still trying to create a my own session system.

However, when I create cookies using a response middleware, they are scoped to the path where they are created. Is it possible to make them global ?

![image](https://user-images.githubusercontent.com/28659185/178034993-fd0658e8-49dd-4f11-892c-98730a0f20d1.png)

**Comment by l2ig** [comment]
You can do so using the 'Set-Cookie' header.

More info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
